const LOGIN_ACTION = 'LOGIN_ACTION';
const WALLET_ACTION = 'WALLET_ACTION';
const API_REQUEST = 'API_REQUEST';
const SEND_EXPENDS = 'SEND_EXPENDS';

export { LOGIN_ACTION, WALLET_ACTION, API_REQUEST, SEND_EXPENDS };
